language: node_js

node_js:
  - "8.7"

before_install:

install:
  - yarn install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - gulp build
  - npm run test:coverage
after_success:
  - npm run codecov
